# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publicar en NPM

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install rimraf
        run: yarn global add rimraf
      - run: yarn install

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - name: Install rimraf
        run: yarn global add rimraf
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: https://registry.npmjs.org/:_authToken' $FWK_LIBS_AUTH_TOKEN;
